# Data merging
This script merged data on Orbis and Orbis IP separately for the given list of Italian firms.

In [1]:
###  setup
import pandas as pd
import glob
 
# the two folders (Orbis = financials, Orbis IP = patents)
orbis_dir    = r"C:\Users\Popov\Documents\Studies\IMT_studies\Projects\Econ_2\Scopus\Initial_Data"
orbis_ip_dir = r"C:\Users\Popov\Documents\Studies\IMT_studies\Projects\Econ_2\Scopus_IP\Initial_Data"

### Financial data (Orbis)

In [2]:
### stack the 3 financial files (strip broken styles first)
import zipfile, io

def read_orbis(path):
    # an xlsx is a zip; rebuild it with an empty styles.xml so openpyxl
    # doesn't choke on Orbis's stylesheet (the applyNumFmt bug)
    buf = io.BytesIO()
    with zipfile.ZipFile(path, "r") as zin:
        with zipfile.ZipFile(buf, "w") as zout:
            for item in zin.namelist():
                data = zin.read(item)
                if item == "xl/styles.xml":
                    # minimal valid empty stylesheet
                    data = (b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                            b'<styleSheet xmlns="http://schemas.openxmlformats.org/'
                            b'spreadsheetml/2006/main"/>')
                zout.writestr(item, data)
    buf.seek(0)
    return pd.read_excel(buf, sheet_name="Results", engine="openpyxl")

fin_files = glob.glob(orbis_dir + r"\*.xlsx")
print(fin_files)

financials = pd.concat([read_orbis(f) for f in fin_files], ignore_index=True)
print(financials.shape) # correct shape

['C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus\\Initial_Data\\Nick_econ2_part2_1.xlsx', 'C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus\\Initial_Data\\Nick_econ2_part2_2.xlsx', 'C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus\\Initial_Data\\Nick_econ2_part2_3.xlsx']

c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")
c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")
c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")

(37042, 74)

In [3]:
financials.sample(3)

,Unnamed: 0,Company name Latin alphabet,BvD ID number,"NACE Rev. 2, core code (4 digits)",Total assets EUR 2024,Total assets USD 2024,Total assets EUR 2023,Total assets USD 2023,Total assets EUR 2022,Total assets USD 2022,...,Added value EUR 2019,Added value USD 2019,Added value EUR 2018,Added value USD 2018,Added value EUR 2017,Added value USD 2017,Added value EUR 2016,Added value USD 2016,Added value EUR 2015,Added value USD 2015
31087,5088.0,STF KEMIM S.R.L. IN LIQUIDAZIONE,IT12152800152,7490.0,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
28246,2247.0,FITNESS BUCCINASCO SRL,IT10782810963,9313.0,498004,517376.126967,480306,530738.368189,n.a.,n.a.,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
3096,3097.0,ITEX S.R.L.,IT00970940946,4617,1364496,1417574.267961,1172570,1295690.43149,669649,714247.280713,...,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.

### Patents data (Orbis IP)

In [4]:
### stack the 7 patent files (reuse read_orbis)
pat_files = glob.glob(orbis_ip_dir + r"\*.xlsx")
print(pat_files)

patents = pd.concat([read_orbis(f) for f in pat_files], ignore_index=True)
print(patents.shape)

['C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus_IP\\Initial_Data\\Nick_econ2_part1_1.xlsx', 'C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus_IP\\Initial_Data\\Nick_econ2_part1_2.xlsx', 'C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus_IP\\Initial_Data\\Nick_econ2_part1_3.xlsx', 'C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus_IP\\Initial_Data\\Nick_econ2_part1_4.xlsx', 'C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus_IP\\Initial_Data\\Nick_econ2_part1_5.xlsx', 'C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus_IP\\Initial_Data\\Nick_econ2_part1_6.xlsx', 'C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus_IP\\Initial_Data\\Nick_econ2_part1_7.xlsx']

c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")
c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")
c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")
c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")
c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")
c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")
c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")

(2265708, 10)

In [5]:
### drop USD columns from financials
usd_cols = [c for c in financials.columns if "USD" in str(c)]
print("dropping:", usd_cols)
financials = financials.drop(columns=usd_cols)
print(financials.shape)

dropping: ['Total assets USD 2024', 'Total assets USD 2023', 'Total assets USD 2022', 'Total assets USD 2021', 'Total assets USD 2020', 'Total assets USD 2019', 'Total assets USD 2018', 'Total assets USD 2017', 'Total assets USD 2016', 'Total assets USD 2015', 'Operating revenue (Turnover) USD 2024', 'Operating revenue (Turnover) USD 2023', 'Operating revenue (Turnover) USD 2022', 'Operating revenue (Turnover) USD 2021', 'Operating revenue (Turnover) USD 2020', 'Operating revenue (Turnover) USD 2019', 'Operating revenue (Turnover) USD 2018', 'Operating revenue (Turnover) USD 2017', 'Operating revenue (Turnover) USD 2016', 'Operating revenue (Turnover) USD 2015', 'Added value USD 2024', 'Added value USD 2023', 'Added value USD 2022', 'Added value USD 2021', 'Added value USD 2020', 'Added value USD 2019', 'Added value USD 2018', 'Added value USD 2017', 'Added value USD 2016', 'Added value USD 2015']
(37042, 44)

In [6]:
### fill the publication number down so every row is tagged to its patent
patents["Publication number"] = patents["Publication number"].ffill()

In [7]:
## drop technical column
patents.drop(columns=[c for c in patents.columns if str(c).startswith("Unnamed")],
             inplace=True, errors="ignore")

## convert Excel date serials to real dates
for col in ["Priority date", "Grant date"]:
    patents[col] = pd.to_datetime(patents[col], unit="D", origin="1899-12-30")
patents.sample(3)

,Publication number,Priority date,Grant date,Number of family members,Family Identifier (Simple),Applicant(s) BvD ID Number(s),IPC code (main),CPC code (main),Backward citations
1759706,US7967433B2,NaT,NaT,NaN,NaN,NaN,NaN,NaN,US6230327B1
2012697,US9978202B2,NaT,NaT,NaN,NaN,NaN,NaN,NaN,US7618323B2
1864437,US8705859B2,NaT,NaT,NaN,NaN,NaN,NaN,NaN,CN1556497A

### Merging

In [8]:
### make matching keys (string, upper, stripped)
# company side:
financials["bvd_key"] = financials["BvD ID number"].astype(str).str.strip().str.upper()
# patent side (the applicant is the company that filed it):
patents["bvd_key"] = patents["Applicant(s) BvD ID Number(s)"].astype(str).str.strip().str.upper()

In [9]:
### SAVE CITATIONS before any filtering (lose nothing)
# each backward-citation value, tagged to its patent via publication number
citations = patents.loc[
    patents["Backward citations"].notna(),
    ["Publication number", "Backward citations"]
].copy()
print("citation links saved:", len(citations))

citation links saved: 1809184

In [10]:
### patent-level table: keep only rows that carry an applicant (can join to a firm)
patents_lvl = patents[patents["Applicant(s) BvD ID Number(s)"].notna()].copy()
print("patent rows with applicant:", len(patents_lvl))

patent rows with applicant: 629225

In [11]:
### company-centric merge (keep every company, attach its patents)
merged = financials.merge(patents_lvl, on="bvd_key", how="left")
merged.drop(columns=[c for c in merged.columns if str(c).startswith("Unnamed")],
            inplace=True, errors="ignore")
print("merged shape:", merged.shape)

merged shape: (436113, 53)

In [12]:
# how many companies matched at least one patent?
matched = merged.loc[merged["Publication number"].notna(), "bvd_key"].nunique()
total   = financials["bvd_key"].nunique()
print(f"{matched} of {total} companies have >=1 patent ({100*matched/total:.1f}%)")

3576 of 37042 companies have >=1 patent (9.7%)

In [13]:
merged.sample(3)

,Company name Latin alphabet,BvD ID number,"NACE Rev. 2, core code (4 digits)",Total assets EUR 2024,Total assets EUR 2023,Total assets EUR 2022,Total assets EUR 2021,Total assets EUR 2020,Total assets EUR 2019,Total assets EUR 2018,...,bvd_key,Publication number,Priority date,Grant date,Number of family members,Family Identifier (Simple),Applicant(s) BvD ID Number(s),IPC code (main),CPC code (main),Backward citations
145705,ELMEC INFORMATICA SPA,IT01490000120,6311,150779225,142171412,132318337,113458788,116524334,90926816,84317076,...,IT01490000120,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN
22228,VALMET TISSUE CONVERTING S.P.A.,IT00145160461,2895,368280775,204151460,202086568,215425568,191800060,187117894,163594180,...,IT00145160461,IT1363743B1,NaT,NaT,1.0,1.149632e+09,IT00145160461,B65B,NaN,NaN
20810,VALMET TISSUE CONVERTING S.P.A.,IT00145160461,2895,368280775,204151460,202086568,215425568,191800060,187117894,163594180,...,IT00145160461,CN1946524A,2004-04-01,NaT,9.0,3.496560e+07,IT00145160461,B26D7/12,B26D7/12,NaN

## Export

In [14]:
### clean column names for Stata, then export all four tables
def clean_cols(df):
    df = df.copy()
    cols = (pd.Index(df.columns).astype(str)
              .str.replace(r"[^0-9a-zA-Z]", "_", regex=True)
              .str.strip("_").str.lower())
    # Stata max var-name length is 32; truncate but keep years distinct
    cols = cols.str[:30]
    # de-duplicate any names that now collide (append _1, _2, ...)
    seen = {}
    out = []
    for c in cols:
        if c in seen:
            seen[c] += 1
            out.append(f"{c[:27]}_{seen[c]}")
        else:
            seen[c] = 0
            out.append(c)
    df.columns = out
    # Stata dislikes mixed object columns -> clean strings
    for c in df.columns:
        if df[c].dtype == object:
            df[c] = df[c].astype(str).replace({"nan": "", "None": "", "<NA>": ""})
    return df

export_dir = r"C:\Users\Popov\Documents\Studies\IMT_studies\Projects\Econ_2\Datasets"

clean_cols(financials ).to_stata(export_dir + r"\financials.dta", write_index=False, version=118)
clean_cols(patents_lvl).to_stata(export_dir + r"\patents.dta",    write_index=False, version=118)
clean_cols(citations  ).to_stata(export_dir + r"\citations.dta",  write_index=False, version=118)
clean_cols(merged     ).to_stata(export_dir + r"\merged.dta",     write_index=False, version=118)
print("exported: financials / patents / citations / merged  (.dta)")

exported: financials / patents / citations / merged  (.dta)

### Owners of cited patents
Separate Orbis IP pull: publication number -> applicant BvD, for the patents our firms cite.

In [18]:
cited_dir = r"C:\Users\Popov\Documents\Studies\IMT_studies\Projects\Econ_2\Scopus_IP\Cited"
cited_files = glob.glob(cited_dir + r"\*.xlsx")
print(cited_files)

cited_owners = pd.concat([read_orbis(f) for f in cited_files], ignore_index=True)
print(cited_owners.shape)

# junk column + continuation rows for multi-applicant patents
cited_owners.drop(columns=[c for c in cited_owners.columns if str(c).startswith("Unnamed")],
                  inplace=True, errors="ignore")
cited_owners["Publication number"] = cited_owners["Publication number"].ffill()

# find the applicant column whatever Orbis named it, build the key
appl_col = [c for c in cited_owners.columns if "bvd" in str(c).lower()][0]
print("using owner column:", appl_col)

cited_owners = cited_owners[cited_owners[appl_col].notna()].copy()
cited_owners["owner_key"] = cited_owners[appl_col].astype(str).str.strip().str.upper()

cited_owners = cited_owners[["Publication number", "owner_key"]].drop_duplicates()
print("pub-owner pairs:", len(cited_owners),
      "| distinct patents:", cited_owners["Publication number"].nunique())

['C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus_IP\\Cited\\Nick_econ2_cited_1.xlsx', 'C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus_IP\\Cited\\Nick_econ2_cited_2.xlsx', 'C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus_IP\\Cited\\Nick_econ2_cited_3.xlsx', 'C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus_IP\\Cited\\Nick_econ2_cited_4.xlsx', 'C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus_IP\\Cited\\Nick_econ2_cited_5.xlsx', 'C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus_IP\\Cited\\Nick_econ2_cited_6.xlsx', 'C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus_IP\\Cited\\Nick_econ2_cited_7.xlsx', 'C:\\Users\\Popov\\Documents\\Studies\\IMT_studies\\Projects\\Econ_2\\Scopus_IP\\Cited\\Nick_econ2_cited_8.xlsx']

c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")
c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")
c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")
c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")
c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")
c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")
c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")
c:\Users\Popov\anaconda3\envs\IMT_studies\Lib\site-packages\openpyxl\styles\stylesheet.py:232: UserWarning: Workbook contains no stylesheet, using openpyxl's defaults
  warn("Workbook contains no stylesheet, using openpyxl's defaults")

(982807, 4)
using owner column: Applicant(s) BvD ID Number(s)
pub-owner pairs: 559652 | distinct patents: 536984

In [19]:
clean_cols(cited_owners).to_stata(export_dir + r"\cited_owners.dta",
                                  write_index=False, version=118)
print("saved cited_owners.dta")

saved cited_owners.dta